#[cfg(test)]
mod test_main {
    use aoc_07::{first, second};

    const DATA: &str = r#".......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."#;

    #[test]
    fn test_first() -> () {
        let first_expected = 21;
        let first_actual = first(DATA.lines());
        assert_eq!(first_expected, first_actual);
    }

    #[test]
    fn test_second() -> () {
        let second_expected = 40;
        let second_actual = second(DATA.lines());
        assert_eq!(second_expected, second_actual);
    }
}
